### ISSUE TITLE
Local copy after running import-disks complaining about no ./Data directory?

### ISSUE THREAD

**Issue by qtqgyt** [mihaip/infinite-mac#259]
Again, I don't really know what more I could include. If you need more info, please ask me.

```danie@CATMANGO:/mnt/c/Users/danie/Documents/infinite-mac$ npm run build

> infinite-mac@0.1.0 build
> vite build

vite v4.4.9 building for production...
✓ 52 modules transformed.
✓ built in 2.62s
Could not resolve "./Data/CD-ROMs.json" from "src/cdroms.ts"
file: /mnt/c/Users/danie/Documents/infinite-mac/src/cdroms.ts
error during build:
RollupError: Could not resolve "./Data/CD-ROMs.json" from "src/cdroms.ts"
    at error (file:///mnt/c/Users/danie/Documents/infinite-mac/node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
    at ModuleLoader.handleInvalidResolvedId (file:///mnt/c/Users/danie/Documents/infinite-mac/node_modules/rollup/dist/es/shared/node-entry.js:24778:24)
    at file:///mnt/c/Users/danie/Documents/infinite-mac/node_modules/rollup/dist/es/shared/node-entry.js:24740:26```

**Comment by qtqgyt** [comment]
I was hoping I would get a response by now :)

**Comment by mihaip** [comment]
You're right at that you need to run `npm run import-cd-roms` to ensure that the CD-ROM library metadata is built. The error you're getting there (`AttributeError: module 'typing' has no attribute 'NotRequired'`) shows that your Python version is too old (3.11 or later is required).

**Comment by qtqgyt** [comment]
> You're right at that you need to run `npm run import-cd-roms` to ensure that the CD-ROM library metadata is built. The error you're getting there (`AttributeError: module 'typing' has no attribute 'NotRequired'`) shows that your Python version is too old (3.11 or later is required).

Thanks! I couldn't find any Info about the error online. Sorry to keep opening random issues :/
