### ISSUE TITLE
Unable to compile on macOS Sonoma - Building system image NeXTSTEP 3.3 HD.dsk

### ISSUE THREAD

**Issue by rocheston** [mihaip/infinite-mac#282]
I am currently experiencing an issue while trying to compile Infinite Mac from the provided GitHub instructions.

Here are the steps I've followed so far:

git clone --recursive https://github.com/mihaip/infinite-mac.git
cd infinite-mac
npm install 
pip3 install -r requirements.txt.
npm run build-xadmaster 

All the commands ran successfully- no issues encountered.

However, when I attempt to run npm run import-disks, I encounter an issue which I am unable to diagnose or solve, and requires your assistance.

I would appreciate any guidance on resolving this issue so I can fully compile and utilize Infinite Mac.

Building system image NeXTSTEP 3.3 HD.dsk
Traceback (most recent call last):
  File "/Users/Jason/Downloads/mac/scripts/import-disks.py", line 727, in <module>
    images.append(build_system_image(disk, temp_dir))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Jason/Downloads/mac/scripts/import-disks.py", line 493, in build_system_image
    with zipfile.ZipFile(input_path, "r") as zip:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/zipfile/__init__.py", line 1339, in __init__
    self._RealGetContents()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/zipfile/__init__.py", line 1406, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

**Comment by rocheston** [comment]
Got it to work. It is git lfs install issue. Thank you for this amazing project. I simply love Nextstep running inside a browser. Amazing work.
