### ISSUE TITLE
import-disks fails with "No such file or directory:" and "Unable to find application named 'BasiliskII'"

### ISSUE THREAD

**Issue by jake-sl** [mihaip/infinite-mac#63]
import-disks fails to run until a 'Disk' folder is manually created in the '/public' directory.

Once fixed, import-disks fails with "Unable to find application named 'BasiliskII'" - Though BasiliskII DID build successfully. 

Log:

`
> infinite-mac@0.1.0 import-disks
> scripts/import-disks.py
Chunking System 7.5.3 HD.dsk: 100.0%
Chunking KanjiTalk 7.5.3 HD.dsk: 100.0%
Chunking Mac OS 8.1 HD.dsk: 100.0%
Importing other images
  Importing Developer/THINK C
  [removed]
Importing .zips
  Importing Developer/THINK Pascal
  [removed]
Rebuilding Desktop DB for Infinite HD.dsk...
Unable to find application named 'BasiliskII'
Traceback (most recent call last):
  File "/Users/user/Desktop/mac22/scripts/import-disks.py", line 500, in <module>
    build_library_image("Infinite HD.dsk")
  File "/Users/user/Desktop/mac22/scripts/import-disks.py", line 451, in build_library_image
    image = build_desktop_db(image, base_name)
  File "/Users/user/Desktop/mac22/scripts/import-disks.py", line 481, in build_desktop_db
    subprocess.check_call([
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['open', '-a', 'BasiliskII', '-W', '--args', '--config', 'none', '--disk', '*/Users/user/Desktop/mac22/scripts/../Images/Mac OS 8.1 HD.dsk', '--disk', '/var/folders/zc/x5bxd1yn3ld2tp5_5_4k2dkw0000gn/T/tmp2rq8hgj2/Infinite HD.dsk', '--extfs', 'none', '--rom', '/Users/user/Desktop/mac22/scripts/../src/Data/Quadra-650.rom', '--screen', 'win/640/480', '--ramsize', '16777216', '--frameskip', '0', '--modelid', '14', '--cpu', '4', '--fpu', 'true', '--nocdrom', 'true', '--nosound', 'true', '--noclipconversion', 'true', '--idlewait', 'true']' returned non-zero exit status 1`

**Comment by jake-sl** [comment]
I was able to resolve the issue by:

1. Adjusting the BasaliskII script permissions to 755
2. Manually specifying the path of the binary in on like 484 of import-disks.py
3. Adding the #!/bin/sh shebang to the top of the BasiliskII script file
